owner: Space-Turtle0
repo: SolamitaHosting


sites:
  - name: Solamita Servers
    url: $URL
    icon: https://cdn.discordapp.com/attachments/415230270694883363/777383668125532180/Solaris_Pirates_Yin_and_Yang.jpg

status-website:
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Solamita Uptime Tracker"
  introMessage: Tracking Solamita and its Uptime!
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
